### ISSUE TITLE
[Suggestions] Comapatability assurance with PPP & Last Tombstone Pins

### ISSUE THREAD

**Issue by Atlasroar** [nbusseneau/BetterCartographyTable#8]
TLDR: 
[PinnaclePinPerformance](https://thunderstore.io/c/valheim/p/ComfyMods/Pinnacle/)
[LastTombstonePin](https://thunderstore.io/c/valheim/p/Frogger/LastTombstonePin/)

> considering bettercartographies feature set i intend to recommend lots of changes to make it the best cartography table mod on the internet for valheim

 :P
 While im not sure that any issues will arise because of the three mods i want to ensure that they dont as i'll be adding this to the optional modpack. LTP also has an MIT license so theoretically could be replicated or integrated to ensure stability of BCT mod

**Comment by Atlasroar** [comment]
Idk how to add labels lol

**Comment by nbusseneau** [comment]
- PPP is a completely different approach in terms of cartography, it's actually precisely because I did not like what PPP does (since it completely voids cartography tables and strays very far away from vanilla) that I decided to do BCT. I don't foresee PPP and BCT being ever compatible due to that.
- LTP is unrelated to cartography, I will not add this feature in BCT but at the same time I see no reason for it to not be compatible out of box.

**Comment by Atlasroar** [comment]
Hmm okay. PPP may be the reason i have gotten new reports of conflicts. Though could also be outdated mods

**Comment by nbusseneau** [comment]
Maybe you could expand on why you wanted to have both PPP and BCT in the first place? What is your vision here, why would both be needed even though we have such different approaches?

**Comment by Atlasroar** [comment]
I dont necessarily "need" them. But the community im building for will ask.

For reference: 
https://youtu.be/c5KSCCMhcFw
https://youtu.be/e034PG9D22I?si=bnHD14omd0-tj6yM
https://youtu.be/6om9GoAznKQ?si=WUWBjnwQ636Qcng_
https://youtu.be/fFINcK3xcfs?si=zPsR9hZ5NNMTLBC2
https://youtu.be/7b8m-Ma0Qxw?si=fwcOIXtsOH0v3efh
https://x.com/JakeSucky/status/1770967438458593521
in total theres something like 5-6 million impressions/views and eyes on the project. So i need to ensure the list im building is as robust as possible to meet minimum expectations but theres also some features i want to have as core items. (better cartography now being one of those items, over something like asocial cartograhpy which we were using previously).

So if i can get compatibility, cool. that helps round out optional mods.
If i cant, that's also cool and saves me time and effort keeping mods up to date.
Any mods not conflicting is also a good thing :) 

You also dont have a discord so harder to spring a single line of thought and question lol.

**Comment by nbusseneau** [comment]
Oh, you're that RPG world community, I see 😄 

> I dont necessarily "need" them. But the community im building for will ask.

I mean, at a glance it seems to me you are one of the persons doing arbitrage between mods and making decisions on vision. So I went with the assumption that you don't put something in the modpack just because someone asked, because any mod that's in is one more liability, whether it is for immediate compatibility with current or future mods, maintenance (especially in case of updates), or user support. Hence why I asked why you need both, to understand the vision you have in mind for your modpack.

To rephrase differently: I went over PPP features on my end once again, and tried to figure out for each one if that was something I thought should be part of BCT. The edit panel is nice but I think is kinda unnecessary / overkill, when we can do it vanilla-like instead. The filtering by name is also nice but also something I don't think is quite necessary for BCT.

In general I err on the side of not implementing things I'm not sure are needed, because they often prove to be more harmful than useful, so that's why I need to discuss use case / needs to be convinced it's a sound addition 😄 

> Any mods not conflicting is also a good thing :)

I am currently reworking BCT internals so that it's more flexible and plays nicer with other mods. As it stands right now it's really not intended for any other mods to do anything with pins, I basically make a bunch of assumptions / optimizations that assume as much. But from testing it seems performance is never an issue anyway so it should be fine if I don't do these, in which case other mods interacting with pins (such as LTP) should not be impacted any more.

> You also dont have a discord so harder to spring a single line of thought and question lol.

Yeah sorry, I actually prefer to keep everything on GitHub... I think it's better, from experience Discord is not a suitable platform for software development-related tasks such as keeping track of feature requests and all. Just want to reiterate that you are most welcome to submit things here, it's just if I don't get the use case / need right away I will generally ask questions and try to dig in to see if it makes sense for me to add in the mod 😉

**Comment by nbusseneau** [comment]
Compatibility with other mods should be greatly improved in version [0.4.0](https://github.com/nbusseneau/BetterCartographyTable/releases/tag/0.4.0).
